[package]
name = "Chompiler"
version = "0.0.0"
authors = ["Jackson Isenberg <jisenberg1050@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"